### PR TITLE
Make schema compatible with cluster-aws

### PR DESCRIPTION
**Pull request by nprokopic**
### What does this PR do?

Updating global property names so they are the same as in cluster-aws.

### CODE REVIEW

**Review by njuettner — APPROVED** [review]
Could you check if we have the cluster autoscaler annotation for machine pools?

IIRC we never added into cluster only on machinepool in cluster-aws

**Comment by nprokopic** [comment]
> Could you check if we have the cluster autoscaler annotation for machine pools?
> 
> IIRC we never added into cluster only on machinepool in cluster-aws

Yeah, it's not there yet. Will add that (in other PRs, not in this one) and few other recent changes we miss from cluster-aws.

**Comment by nprokopic** [comment]
Also I think we can fix the CI here now, after all the work in schemalint and schemadocs.

**Comment by nprokopic** [comment]
For this PR this being 🟢 is important :)

> Compare Helm Rendering / check-cmp-state (pull_request)

**Pull request merged**
