### PR TITLE
Removed outdated TLS cipher suites

### PR DESCRIPTION
**Pull request by njuettner**
**Feature release for v30 releases**

Dropping two outdated cipher suites, there's already a newer version included for both *_SHA256.

Towards: https://github.com/giantswarm/roadmap/issues/3766

- [x] CHANGELOG.md has been updated (if it exists)

### CODE REVIEW

**Comment by Gacko** [comment]
Once ready, we should include this in the v30 releases earliest as it could be a breaking change. Or could you at least write a warning in the CHANGELOG.md so nobody forgets about it when including in the provider specific cluster charts and workload cluster releases?

**Comment by njuettner** [comment]
@AndiDog could you PTAL?

**Review by Gacko — APPROVED** [review]

**Review by AverageMarcus — APPROVED** [review]

**Review by Gacko — APPROVED** [review]

**Review by Gacko — APPROVED** [review]

**Comment by njuettner** [comment]
@AndiDog does that work for you 🙂, if you're fine with it I'm going to merge it

**Comment by njuettner** [comment]
Going with a ping

**Pull request merged**
