### PR TITLE
Release v1.5.0

### PR DESCRIPTION
**Pull request by taylorbot**

### CODE REVIEW

**Review by Gacko — APPROVED** [review]

**Review by Gacko — CHANGES_REQUESTED** [review]
I don't know how urgent this is, but can we maybe wait until https://github.com/giantswarm/cluster/pull/348 got merged? @fiunchinho, what's the current state of your work?

**Comment by glitchcrab** [comment]
> I don't know how urgent this is, but can we maybe wait until #348 got merged? @fiunchinho, what's the current state of your work?

I'm currently blocked until this is released so it's quite urgent for me.

**Review by Gacko — APPROVED** [review]
Happy to unblock you, would have been a dream to also get Jose's work into this release though. 🙂

**Comment by Gacko** [comment]
In the end it's just numbers. 🤪

**Comment by fiunchinho** [comment]
> I don't know how urgent this is, but can we maybe wait until #348 got merged? @fiunchinho, what's the current state of your work?

I'd like an approval from someone from Phoenix before merging mine. I'll ping them.

**Comment by Gacko** [comment]
Thank you for responding! I hope you're fine with not having it included in the current release. We can still forge a v1.6.0 for your changes only then! 🙂

**Comment by Gacko** [comment]
... on the other hand: If Wealdy waits a bit longer and Phoenix hurries up... 😅

**Comment by fiunchinho** [comment]
I'm fine either way :slightly_smiling_face: I pinged phoenix people, but it's been a busy day so far.

**Comment by glitchcrab** [comment]
> I'm fine either way 🙂 I pinged phoenix people, but it's been a busy day so far.

It's not a big deal to wait a little longer :) i'm using the test builds of the chart to do my testing in VCD so i can work on that until this is merged.

**Comment by glitchcrab** [comment]
I'm going to close this PR for now as I would like to get #355 into the same release too (as it extends the systemd options)

**Pull request closed without merging**
